### ISSUE TITLE
Unable to deserialize miner box file

### ISSUE THREAD

**Issue by ex3ndr** [toncenter/tonweb#13]
I just generated test boc and it is not possible to load it in any way.

```4D696E65006123D297F5A361CB6296AA6C460F810C0670AA84A1E343935FF6CD91FCFDEF7B0FE21CBACBA24853DFE044970C8F95B5F3E797F6AAABA150536E47D48A5BA08BD4EDB0F5D87D353BB25238528DBF34B9FE49FA8ECBA24853DFE044970C8F95B5F3E797F6AAABA150536E47D48A5BA08BD4EDB0F5```

**Comment by EmelyanenkoK** [comment]
This string is not a correct boc serialization.
I have generated boc file via miner right now:
`b5ee9c724101020100a100014589ff1ffa673b838143a00b8f08349010666295b88ef4eb3a58419668fca0e1b4e0600c0100f24d696e650060fb599bc6a52e800e5df23827350a559463e6c70da115b532f1e9f63f4426cb3128cfc52b018baf1e933a1c06a3201515f1aeebfc8e20b52c04ae634dc81c71dad990e0ea4f3386401a9768335ca8c11061b81a2b018baf1e933a1c06a3201515f1aeebfc8e20b52c04ae634dc81c71dad990e01f363128`

To deserialize it with Tonweb one needs to do the following:
```js
TonWeb.boc.Cell.fromBoc(
  TonWeb.utils.hexToBytes(
      "b5ee9c724101020100a100014589ff1ffa673b838143a00b8f08349010666295b88ef4eb3a58419668fca0e1b4e0600c0100f24d696e650060fb599bc6a52e800e5df23827350a559463e6c70da115b532f1e9f63f4426cb3128cfc52b018baf1e933a1c06a3201515f1aeebfc8e20b52c04ae634dc81c71dad990e0ea4f3386401a9768335ca8c11061b81a2b018baf1e933a1c06a3201515f1aeebfc8e20b52c04ae634dc81c71dad990e01f363128"
  )
)
```

**Comment by ex3ndr** [comment]
You were right! I picked not a file, but the string that was printed by miner. Thanks!
