### ISSUE TITLE
test-highload script doesn't work with mainnet

### ISSUE THREAD

**Issue by dattran92** [toncenter/tonweb#131]
I tried this script.
https://github.com/toncenter/tonweb/blob/master/src/test-highload.js

It works with testnet.
but when I changed to mainnet, I get the error below:

```
LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted
Cannot run message on account: inbound external message rejected by transaction 8CE3F72FA4F4E0FE5052D9CA7495B6F8E44380D102CEB2B0237BDFEEE91157B4:
exitcode=0, steps=0, gas_used=0
```

Could you assist?

**Comment by not-difhel** [comment]
@dattran92, how did you solve the problem? I have the same
