### ISSUE TITLE
Is API backend proprietary?

### ISSUE THREAD

**Issue by ex3ndr** [toncenter/tonweb#14]
Does API endpoint that is used by TonWeb wallet open source?

**Comment by EmelyanenkoK** [comment]
[pyTON](https://github.com/EmelyanenkoK/pyTON) with webserver serves as backend (in particular toncenter.com runs pyTON)
Current sources a little bit outdated: user need to recompile libtonlibjson from https://github.com/newton-blockchain/ton.
In a week or two pyTONv3 (fully compatible but more stable and with more features) will be released.
