### ISSUE TITLE
Sending tons

### ISSUE THREAD

**Issue by h1rdr3v2** [toncenter/tonweb#147]
Please can someone write a code that would transfer tons from your wallet to another wallet.
Please don't point me to documentation, as i have tried using it, either i end at some scrambled message or crazy error.
Please just one simple script that works let me see.
I

**Comment by triplepppp** [comment]
30000not price
Send UQCp3OBa7YCoLlOVrrnB9S9n0j5EXcdYBS9eKXv8e8c-eOd1 and write you e-mail
