### ISSUE TITLE
 tontp мошенники?

### ISSUE THREAD

**Issue by Aleksei-Sharandin** [toncenter/tonweb#198]
Здравствуйте, объясните пожалуйста что такое tontp, это скам? Случайно даже не понял как это вышло все мои средства обменялись на эту монету.
Возможно это как то исправить?
![upload_2024_07_10_09_09_22_967](https://github.com/toncenter/tonweb/assets/175186265/f6cde0bb-ce69-4033-a18b-293288856575)

**Comment by TonyDEv-lab** [comment]
@Aleksei-Sharandin It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Chatbotist** [comment]
Я пополнил баланс в TON и получил уведомление, что я могу покрутить колесо фортуны в уведомлении пополнения моего баланса на 0,00001 USDT, Перешел по ссылке и там крутил колесо фортуны, выиграл что-то и нажал кнопку получить, а там у меня стоит выбор, заплатить за контракт и получить как-раз этот токен, стал искать информацию и набрел на это место, решил поделиться тем, что было, больше пока не знаю

В интернете пишут, что это скам
https://tonviewer.com/EQDv5gg_0TUJ9HtZ2Vrp-oSinF7thXFofcuSQIhUf-bhz-JL?section=nft


![tonkeeper](https://github.com/user-attachments/assets/1790f84d-cb03-4597-8819-31d2ea64e5ea)
![скам](https://github.com/user-attachments/assets/494091c8-06fb-4192-bfb1-d0774db36b48)
![usdt](https://github.com/user-attachments/assets/387f3b84-895d-430c-b0b4-443a9d5b488b)

**Comment by iamDonkey** [comment]
Это мошенничество. Вам следует отключить свой кошелек tonkeeeper от этого мошеннического сайта и воздерживаться от подключения кошелька к неизвестным веб-сайтам.
