### ISSUE TITLE
Не вернули тоны и не пришли Моны хамстел

### ISSUE THREAD

**Issue by Rodion1411** [toncenter/tonweb#200]
Подскажите пополнил кошелек тонкипер на 5 тон, чтобы дали монеты хамстел комбат, все сняли и тоны и ноткоины ничего нет! Что делать помогите
![Screenshot_20240711-150111](https://github.com/user-attachments/assets/a7a32602-4982-448f-bc33-88895fc77b49)
****

**Comment by Shahmokhiyan** [comment]
ارسال شده از دستگاه Galaxy من
-------- پیام اصلی --------از: Rodion1411 ***@***.***> تاریخ: ۲۰۲۴/۷/۱۲  ۰۶:۰۶  (GMT+03:30) گیرنده: toncenter/tonweb ***@***.***> گیرنده کپی: Subscribed ***@***.***> موضوع [toncenter/tonweb] Не вернули тоны и не пришли Моны хамстел (Issue #200) 
Подскажите пополнил кошелек тонкипер на 5 тон, чтобы дали монеты хамстел комбат, все сняли и тоны и ноткоины ничего нет! Что делать помогите
Screenshot_20240711-150111.png (view on web)
