### ISSUE TITLE
Вы меня обманули

### ISSUE THREAD

**Issue by Wika1993** [toncenter/tonweb#226]
Я перевела вам тон,  вы их получили и на этом все. Верните мне мои деньги. У меня 4 детей. Каждая копейка на счету. Вам не стыдно?

**Comment by Wika1993** [comment]
Карма вас настигнет. Обокрали людей. Не думайте что вам это сойдёт с рук

**Comment by Dappnode0xa** [comment]
@Wika1993 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Dark1987d** [comment]
> Карма вас настигнет. Обокрали людей. Не думай, что тебе это придет с руками

Здесь наиобка
