### ISSUE TITLE
error on wallet deploy

### ISSUE THREAD

**Issue by sg-milad** [toncenter/tonweb#239]
I'm trying to deploy my wallet like the docs but I have an error
docs
```ts 
const tonweb = new TonWeb();

const wallet = tonweb.wallet.create({publicKey});

const address = await wallet.getAddress();

const nonBounceableAddress = address.toString(true, true, false);

const seqno = await wallet.methods.seqno().call();

await wallet.deploy(secretKey).send(); // deploy wallet to blockchain
```
my code:
```ts
async deployWallet(publicKey: string, secretKey: Uint8Array) {
    console.log("Public Key:", publicKey);
    console.log("Secret Key length:", secretKey.length); // length: 32

    try {
        const wallet = this.tonWeb.wallet.create({ publicKey });
        console.log("Wallet created");

        const seqno = await wallet.methods.seqno().call();
        console.log("Initial seqno:", seqno);

        const deployResult = await wallet.deploy(secretKey).send();
        console.log("Deployment result:", deployResult);
    } catch (error) {
        console.error("Deployment error:", error);
        throw error;
    }
}
```
error:
writeUint: value is NaN
    at BitString.writeUint (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@51.0.26_@babel+core@7.25.2_@babel+preset-env@7.25.3_@babel+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu/node_modules/tonweb/src/boc/BitString.js:118:34)
    at BitString.writeUint8 (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@51.0.26_@babel+core@7.25.2_@babel+preset-env@7.25.3_@babel+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu/node_modules/tonweb/src/boc/BitString.js:177:14)
    at BitString.writeBytes (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@51.0.26_@babel+core@7.25.2_@babel+preset-env@7.25.3_@babel+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu/node_modules/tonweb/src/boc/BitString.js:186:18)
    at WalletV3ContractR1.createDataCell (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@51.0.26_@babel+core@7.25.2_@babel+preset-env@7.25.3_@babel+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu/node_modules/tonweb/src/contract/wallet/WalletContractV3.js:39:19)
    at WalletV3ContractR1.createStateInit (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@51.0.26_@babel+core@7.25.2_@babel+preset-env@7.25.3_@babel+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu/node_modules/tonweb/src/contract/index.js:51:31)
    at WalletV3ContractR1.getAddress (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@51.0.26_@babel+core@7.25.2_@babel+preset-env@7.25.3_@babel+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu/node_modules/tonweb/src/contract/index.js:22:40)
    at TonService.deployWallet (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/ton.service.ts:127:42)
    at TonService.transfer (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/ton.service.ts:94:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AudioConsumer.process (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/queues/transaction.queue.ts:29:26)

**Comment by knox0506** [comment]
ok

**Comment by knox0506** [comment]
ok

**Comment by knox0506** [comment]
> I'm trying to deploy my wallet like the docs but I have an error docs
> 
> ```ts
> const tonweb = new TonWeb();
> 
> const wallet = tonweb.wallet.create({publicKey});
> 
> const address = await wallet.getAddress();
> 
> const nonBounceableAddress = address.toString(true, true, false);
> 
> const seqno = await wallet.methods.seqno().call();
> 
> await wallet.deploy(secretKey).send(); // deploy wallet to blockchain
> ```
> 
> my code:
> 
> ```ts
> async deployWallet(publicKey: string, secretKey: Uint8Array) {
>     console.log("Public Key:", publicKey);
>     console.log("Secret Key length:", secretKey.length); // length: 32
> 
>     try {
>         const wallet = this.tonWeb.wallet.create({ publicKey });
>         console.log("Wallet created");
> 
>         const seqno = await wallet.methods.seqno().call();
>         console.log("Initial seqno:", seqno);
> 
>         const deployResult = await wallet.deploy(secretKey).send();
>         console.log("Deployment result:", deployResult);
>     } catch (error) {
>         console.error("Deployment error:", error);
>         throw error;
>     }
> }
> ```
> 
> error: writeUint: value is NaN at BitString.writeUint (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/boc/BitString.js:118:34) at BitString.writeUint8 (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/boc/BitString.js:177:14) at BitString.writeBytes (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/boc/BitString.js:186:18) at WalletV3ContractR1.createDataCell (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/contract/wallet/WalletContractV3.js:39:19) at WalletV3ContractR1.createStateInit (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/contract/index.js:51:31) at WalletV3ContractR1.getAddress (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/contract/index.js:22:40) at TonService.deployWallet (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/ton.service.ts:127:42) at TonService.transfer (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/ton.service.ts:94:28) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at AudioConsumer.process (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/queues/transaction.queue.ts:29:26)

ok

**Comment by sg-milad** [comment]
> I'm trying to deploy my wallet like the docs but I have an error docs
> 
> ```ts
> const tonweb = new TonWeb();
> 
> const wallet = tonweb.wallet.create({publicKey});
> 
> const address = await wallet.getAddress();
> 
> const nonBounceableAddress = address.toString(true, true, false);
> 
> const seqno = await wallet.methods.seqno().call();
> 
> await wallet.deploy(secretKey).send(); // deploy wallet to blockchain
> ```
> 
> my code:
> 
> ```ts
> async deployWallet(publicKey: string, secretKey: Uint8Array) {
>     console.log("Public Key:", publicKey);
>     console.log("Secret Key length:", secretKey.length); // length: 32
> 
>     try {
>         const wallet = this.tonWeb.wallet.create({ publicKey });
>         console.log("Wallet created");
> 
>         const seqno = await wallet.methods.seqno().call();
>         console.log("Initial seqno:", seqno);
> 
>         const deployResult = await wallet.deploy(secretKey).send();
>         console.log("Deployment result:", deployResult);
>     } catch (error) {
>         console.error("Deployment error:", error);
>         throw error;
>     }
> }
> ```
> 
> error: writeUint: value is NaN at BitString.writeUint (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/boc/BitString.js:118:34) at BitString.writeUint8 (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/boc/BitString.js:177:14) at BitString.writeBytes (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/boc/BitString.js:186:18) at WalletV3ContractR1.createDataCell (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/contract/wallet/WalletContractV3.js:39:19) at WalletV3ContractR1.createStateInit (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/contract/index.js:51:31) at WalletV3ContractR1.getAddress (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/node_modules/.pnpm/tonweb@0.0.66_expo@[51.0.26_@babel](mailto:51.0.26_@babel)+core@[7.25.2_@babel](mailto:7.25.2_@babel)+preset-env@[7.25.3_@babel](mailto:7.25.3_@babel)[+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu](mailto:+core@7.25.2___r_izqagi3dk6dswnbb3h265kzjdu)/node_modules/tonweb/src/contract/index.js:22:40) at TonService.deployWallet (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/ton.service.ts:127:42) at TonService.transfer (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/ton.service.ts:94:28) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at AudioConsumer.process (/home/sg-milad/Downloads/clone/ton-crypto-payment-system/src/ton/queues/transaction.queue.ts:29:26)

after debugging I found out my secret key was invalid
