### ISSUE TITLE
doesn't work with webpack 5 and vitejs

### ISSUE THREAD

**Issue by alygee** [toncenter/tonweb#30]
Error occurs when importing TonWeb
`Uncaught ReferenceError: Buffer is not defined`

**Comment by slavafomin** [comment]
There are plans to implement proper ESM-compatible builds with the tree-shaking support in the future. Stay tuned.

**Comment by slavafomin** [comment]
Hello! Thank you for your error report.

However, could you please share a stack trace and the code that causes this exception to occur? Also, what environment are you using (node/browser)?

**Comment by NoelJacob** [comment]
Hey @alygee how did you solve it? Was there anyway without poly-filling?

**Comment by n1203** [comment]
> Hey @alygee how did you solve it? Was there anyway without poly-filling?

same question.... why closed? This problem has not been resolved.
