### ISSUE TITLE
const transferSended = await transfer.send();  // send transfer query to blockchain

### ISSUE THREAD

**Issue by Serg95off** [toncenter/tonweb#53]
Please help me!
I send transfer query to blockchain
const transferSended = await transfer.send();  
and I get an answer { '@type': 'ok', '@extra': '1651442623.857807:10:0.6998361826917181' }
what is '@extra' ? 
which means '1651442623.857807:10:0.6998361826917181'  ?
How to get the transaction ID ?

**Comment by EmelyanenkoK** [comment]
`@extra` is request id assigned by Toncenter, you can safely ignore this.
There is no way to get txId when you send message because when it is sent, it is not yet known which tx it will produce: for messages which may be replayed one message may produce many transactions (or more precisely many copies of the message will produce many transactions).
To get transaction ID you may check transactions on target address and find required by matching `in` message.

**Comment by Serg95off** [comment]
What should I do if I need to transfer TONS from one wallet to another? 
I have wallet_1, wallet_2 and secretKey_wallet_1
```
let wallet = tonweb.wallet.create({address: 'wallet_1'});
const seqno = await wallet.methods.seqno().call(); 
const transfer = wallet.methods.transfer({
    secretKey: secretKey_wallet_1,
    toAddress: 'wallet_2',
    amount: TonWeb.utils.toNano(10.21),
    seqno: seqno,
    payload: 'Hello',
    sendMode: 3,
});
const transferSended = await transfer.send()
```
Can it be done differently?

**Comment by EmelyanenkoK** [comment]
>Can it be done differently?
Why? Is there something wrong with that approach?

**Comment by Serg95off** [comment]
It constantly gives an error, I have wallet_1, wallet_2 and secretKey_wallet_1 parameters of the String data type. 
`//"secretKey":"60d7b4c7d2223d769df5fdb586892c24ef8cc5a0e3d1197b044eacee3f2fe16c96448ba6cc465421b7a0ba0987ff62889c4ab55db99fdf1203cb40ec073f953d",
//"publicKey":"96448ba6cc465421b7a0ba0987ff62889c4ab55db99fdf1203cb40ec073f953d",
//"wallet":"EQBMiZIjQJuVW6kjcp0gsKSukJ06paac7VrDIWGkE0LPqQQe"}

//"publicKey":"901d0c381fce825ae45ad48539238e5345500ade381327b4f74748afeaa7a0ac",
//"wallet":"EQA6a8y6LphnZSwLnbJQqyYzrHhdal35QWW9Uzv4BLbvyf21"}

const TonWeb = require('tonweb');
const nacl = TonWeb.utils.nacl;
const start = async () => {
let wallet = TonWeb.wallet.create({address: 'EQBMiZIjQJuVW6kjcp0gsKSukJ06paac7VrDIWGkE0LPqQQe'});
const seqno = await wallet.methods.seqno().call(); 
const transfer = wallet.methods.transfer({
    secretKey: '60d7b4c7d2223d769df5fdb586892c24ef8cc5a0e3d1197b044eacee3f2fe16c96448ba6cc465421b7a0ba0987ff62889c4ab55db99fdf1203cb40ec073f953d',
    toAddress: 'EQA6a8y6LphnZSwLnbJQqyYzrHhdal35QWW9Uzv4BLbvyf21',
    amount: TonWeb.utils.toNano(0.21),
    seqno: seqno,
    payload: 'Hello',
    sendMode: 3,
});
const transferSended = await transfer.send();
console.log(transferSended);
}
start();`
what am I doing wrong?
or How can I make a BOС file? For sending via https://toncenter.com/api/v2/#/send/send_boc_sendBoc_post
